---
- name: Install Google Chrome
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Chocolatey if not already installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Google Chrome
      win_chocolatey:
        name: firefox
        state: present
