---
- name: Install Apache2
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Apache2 package
      apt:
        name: apache2
        state: present
      become: yes

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
      become: yes
