---
- name: Install New Soft
  hosts: all
  become: yes

  tasks:
    - name: apt update
      apt:
        update_cache: yes

      
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce and docker-compose
      apt:
        pkg:
          - docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker
        
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
      become: yes
      
    - name: Install pytho3-pip
      apt:
        name:
          - python3-pip
          - groff
          - less
        state: present
      become: yes

    - name: Install AWS CLI
      pip:
        name: awscli
        state: latest
      become: yes
